name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /var/www/html/
        remote_host: ec2-3-133-38-120.us-east-2.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
